# Generated by Django 5.1.4 on 2025-01-08 07:03

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=255)),
                ('total_member', models.IntegerField(default=0)),
                ('company_type', models.CharField(choices=[('IT', 'IT'), ('NON-IT', 'Non-IT'), ('AGRICULTURAL', 'Agricultural'), ('LOW-FARM', 'Low-Farm'), ('PUBLIC-SERVICE', 'Public Service'), ('GOV.', 'Government')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('present_location', models.CharField(max_length=255)),
                ('current_location', models.CharField(max_length=255)),
                ('occupation', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=10)),
                ('about_me', models.TextField(blank=True, null=True)),
                ('which_company', models.CharField(blank=True, max_length=100, null=True)),
                ('position', models.CharField(choices=[('CEO', 'CEO'), ('CTO', 'CTO'), ('MANAGER', 'Manager'), ('MARKETING-TEAM', 'Marketing Team'), ('TEAM-LEADER', 'Team Leader'), ('EMPLOYEE', 'Employee'), ('CUSTOMER-CARE', 'Customer Care')], max_length=20)),
                ('password', models.CharField(max_length=255)),
                ('photos', models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyTargeted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targeted_members', to='api.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targeted_company', to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='UserUploadPictureInServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_photo', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_pictures', to='api.user')),
            ],
        ),
    ]
